# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keelin Jacobsen // Design + Code
email: hi@keel.in
description: Keelin Jacobsen is a Digital Designer & Developer specializing in UI Design and Front-End Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.keel.in" # the base hostname & protocol for your site
twitter_username: KeelinJ
github_username:  KeelinJ
permalink: /:title

# Build settings
markdown: kramdown
